name: Build

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Test
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: |
          yarn test